server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
          filters:
            - AddRequestHeader=Bearer,AccessToken
            - AddResponseHeader=responseHeader,addedResponseFromGw

        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/order/**
          filters:
            - AddRequestHeader=Bearer,AccessToken
            - AddResponseHeader=responseHeader,addedResponseFromGw

        - id: payment-service
          uri: http://localhost:8083
          predicates:  # predicates 조건을 충족할 경우 http://localhost:8083 으로 라우팅
            - Path=/payment/**
#            - Method=POST
#            - Header=X-Request-Id, \d+
          filters:
            - AddRequestHeader=Bearer,AccessToken
            - AddResponseHeader=responseHeader,addedResponseFromGw

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: gateway


