server:
  port: 8080  # 게이트웨이 서버의 주소는 http://localhost:8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        # user-service 서버의 주소는 http://localhost:8081
        - id: user-service
          uri: http://localhost:8081
          predicates:
            # http://localhost:8080/user/** 요청이 게이트웨이 서버로 들어오면 user-service 서버로 라우팅
            - Path=/user/**

        # order-service 서버의 주소는 http://localhost:8082
        - id: order-service
          uri: http://localhost:8082
          predicates:
            # http://localhost:8080/order/** 요청이 게이트웨이 서버로 들어오면 user-service 서버로 라우팅
            - Path=/order/**

        - id: payment-service
          uri: http://localhost:8083
          predicates:
            - Path=/pay/**

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: gateway


