spring:
  application:
    name: demo

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always





resilience4j:
  circuitbreaker:
    configs:
      default:
#        minimumNumberOfCalls: 5
#        slowCallDurationThreshold: 100
#        slidingWindowSize: 10
#        failureRateThreshold: 51
#        waitDurationInOpenState: 10s
        registerHealthIndicator: true




#resilience4j:
#  circuitbreaker:
#    failure-rate-threshold: 10   # ?? 10% ?? ? ?? ??
#    slow-call-duration-threshold: 500   # 500ms ?? ?? ? ??? ??
#    slow-call-rate-threshold: 10   # slowCallDurationThreshold ?? ??? 10% ?? ? ?? ??
#    wait-duration-in-open-state: 30000   # OPEN -> HALF-OPEN ?? ? ???? ??
#    minimum-number-of-calls: 50   # ??? ??? ?? ?? ?
#    sliding-window-size: 100   # ?? CLOSE ???? N? ?? ?? ? failureRateThreshold ?? ?? ??
#    permitted-number-of-calls-in-half-open-state: 30   # HALFOPEN -> CLOSE or OPEN ?? ???? ?? ?? ??
#  retry:
#    wait-duration: 100   # ??? ?? ??
#    max-attempts: 2   # ??? ??(?? ?? ??)
