server:
  port: 8080

spring:
  application:
    name: demo

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default:
#        minimumNumberOfCalls: 5
#        slowCallDurationThreshold: 100
#        slidingWindowSize: 10
#        failureRateThreshold: 51
#        waitDurationInOpenState: 10s
        registerHealthIndicator: true
