version: '3.7'

services:
  user:
    build:
      context: .
      dockerfile: Dockerfile
    image: user
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081

  order:
    build:
      context: .
      dockerfile: Dockerfile
    image: order
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082

  pay:
    build:
      context: .
      dockerfile: Dockerfile
    image: pay
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
